name: ci

on:
  push:
    branches: [main, renovate/**]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: debug

jobs:
  lint-renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        file:
          - default
          - personal
          - renovate-config
          # .github/renovate.json is validated by `renovate` during loading for each preset.
          # - .github/renovate
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4

      - name: Validating ${{ matrix.file }}
        run: npx -p renovate renovate-config-validator
