---
# Renovate this repository if this workflow file or the Renovate configuration file is changed.
name: Renovate

'on':
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches: [main]
    paths:
      - '.github/workflows/renovate.yaml'
      - '.github/renovate.json5?'
  schedule:
    - cron: '0 */30 * * *' # Run every 30 minutes
  workflow_dispatch:
    inputs:
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false

permissions: {}

jobs:
  should-renovate:
    name: Check if Renovate should run
    if: >-
      (github.event_name != 'issues' && github.event_name != 'pull_request') ||
      (
        contains(join(github.event.*.body, ''), '- [x] <!-- approve-all-pending-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- approve-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- approvePr-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- create-all-rate-limited-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- manual job -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- other-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-all-open-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-check -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- recreate-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- retry-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- unlimit-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- unschedule-branch=')
      )
    outputs:
      renovate: ${{ steps.create-output.outputs.renovate }}
    runs-on: ubuntu-latest
    steps:
      - id: create-output
        run: echo "renovate=true" >> $GITHUB_OUTPUT

  renovate:
    if: needs.should-renovate.outputs.renovate == 'true'
    name: Renovate
    needs: should-renovate
    runs-on: ubuntu-latest
    steps:
      - name: Renovate
        uses: bfra-me/renovate-action@3fbecbc49a2a7ddc24bd2e36a3be9d1068adb7f0 # v2.1.26
        with:
          autodiscover: true
          print_config: ${{ inputs.print_config || 'false' }}
          renovate_app_id: ${{ secrets.APPLICATION_ID }}
          renovate_app_pem: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          renovate_app_slug: mrbro-bot
