---
# Renovate this repository if this workflow file or the Renovate configuration file is changed.
name: Renovate

'on':
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches: ['**']
  schedule:
    - cron: '*/30 * * * *' # Run every 30 minutes
  workflow_dispatch:
    inputs:
      print_config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: {}

jobs:
  should-renovate:
    name: Check if Renovate should run
    if: >-
      (github.event_name != 'issues' && github.event_name != 'pull_request') ||
      (
        contains(join(github.event.*.body, ''), '- [x] <!-- approve-all-pending-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- approve-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- approvePr-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- create-all-rate-limited-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- manual job -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- other-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-all-open-prs -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- rebase-check -->') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- recreate-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- retry-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- unlimit-branch=') ||
        contains(join(github.event.*.body, ''), '- [x] <!-- unschedule-branch=')
      )
    outputs:
      renovate: ${{ steps.create-output.outputs.renovate }}
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - if: github.event_name == 'push'
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          filters: |
            changes:
              - '.github/workflows/renovate.yaml'
              - '.github/renovate.json5'
      - id: create-output
        if: github.event_name != 'push' || steps.filter.outputs.changes == 'true'
        run: echo 'renovate=true' >> $GITHUB_OUTPUT

  renovate:
    if: needs.should-renovate.outputs.renovate == 'true'
    name: Renovate
    needs: should-renovate
    runs-on: ubuntu-latest
    steps:
      - name: Renovate
        uses: bfra-me/renovate-action@6dc559aa46519a99c6cf514ed1de180956067643 # v2.2.5
        with:
          autodiscover: ${{ !contains('["issues", "pull_request"]', github.event_name) && github.ref == 'refs/heads/main' }}
          branch: ${{ github.ref != 'refs/heads/main' && github.ref_name || '' }}
          dry_run: ${{ github.event_name == 'push' && !contains('["main", "renovate/reconfigure"]', github.ref_name) }}
          print_config: ${{ inputs.print_config }}
          renovate_app_id: ${{ secrets.APPLICATION_ID }}
          renovate_app_pem: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          renovate_app_slug: 'mrbro-bot'
