---
# Renovate this repository if Renovate-specific tasks are checked, if this workflow file or the Renovate configuration file is changed, or if dispatched.
name: Renovate

on:
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches-ignore: [main]
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_call:
    inputs:
      log-level:
        description: Log level for Renovate
        type: string
        default: debug
      print-config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        type: boolean
        default: false
    secrets:
      APPLICATION_ID:
        description: GitHub App ID
        required: true
      APPLICATION_PRIVATE_KEY:
        description: GitHub App private key
        required: true
  workflow_dispatch:
    inputs:
      log-level:
        description: Log level for Renovate
        required: false
        type: string
        default: debug
      print-config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false
  workflow_run:
    branches: [main]
    types: [completed]
    workflows: [main]

permissions:
  contents: read

jobs:
  renovate:
    name: Renovate
    if: >-
      (github.event.action == 'edited' && !contains(github.actor, '[bot]')) ||
      (
        !contains('["issues", "pull_request", "workflow_run"]', github.event_name) ||
        github.event.workflow_run.conclusion == 'success'
      )
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/renovate.yaml@efaccdb757d5f42e3a43df85c6c626d34ae41418 # v4.0.10
    with:
      log-level: ${{ inputs.log-level || vars.WORKFLOW_LOG_LEVEL || 'debug' }}
      print-config: ${{ inputs.print-config || github.event_name == 'push' }}
