---
# Renovate this repository if Renovate-specific tasks are checked, if this workflow file or the Renovate configuration file is changed, or if dispatched.
name: Renovate

on:
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches: ['**']
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_call:
    inputs:
      log-level:
        description: Log level for Renovate
        type: string
        default: debug
      print-config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        type: boolean
        default: false
    secrets:
      APPLICATION_ID:
        description: GitHub App ID
        required: true
      APPLICATION_PRIVATE_KEY:
        description: GitHub App private key
        required: true
  workflow_dispatch:
    inputs:
      log-level:
        description: Log level for Renovate
        required: false
        type: string
        default: debug
      print-config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false
  workflow_run:
    branches: [main]
    types: [completed]
    workflows: [main]

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  renovate:
    name: Renovate
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/renovate.yaml@f0bfb00d23735cd50b40d557f5054afffb1205dc # v2.6.1
    with:
      log_level: ${{ inputs.log-level || vars.WORKFLOW_LOG_LEVEL || 'debug' }}
      print_config: ${{ inputs.print-config || github.event_name == 'push' }}
