# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

'on':
  push:
    branches: [main]
  schedule:
    - cron: '55 2 * * *' # Every day at 02:55 UTC
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@78a2230b33cd0c0289dc4f322c203dd88f6274ca # v2.0.1
