# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repo Settings

'on':
  push:
    branches: [main]
  schedule:
    - cron: '55 2 * * *' # Every day at 02:55 UTC
  workflow_dispatch:

jobs:
  update-repo-settings:
    name: Update Repo Settings
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/update-repo-settings.yaml@602b6872f87b8590ca3129d9656751ad90ede162 # v2.3.4
