# Update repository settings to match the definitions in .github/settings.yml.
---
name: Update Repository Settings

'on':
  push:
  schedule:
    - cron: '15 14 * * *' # Every day at 14:15 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: {}

jobs:
  update-repo-settings:
    name: Update Repository Settings
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push' && github.ref =='refs/heads/main'
        name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - id: filter
        if: github.event_name == 'push' && github.ref =='refs/heads/main'
        name: Filter Changed Files
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        with:
          filters: |
            changes:
              - 'common-settings.yaml'
              - '.github/settings.yml'
              - '.github/workflows/update-repo-settings.yaml'

      - id: get-workflow-access-token
        if: github.event_name != 'push' || steps.filter.outputs.changes == 'true'
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        name: Get Workflow Access Token
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          permissions: 'administration:write, contents:read, issues:write'

      - env:
          GITHUB_TOKEN: ${{ steps.get-workflow-access-token.outputs.token }}
        if: github.event_name != 'push' || steps.filter.outputs.changes == 'true'
        name: Update Repository Settings (${{ github.repository_owner }}/.github)
        uses: elstudio/actions-settings@v3-beta
